### PR TITLE
3.1.0

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

Updated the layout of the dropdown to include new branding according to this design: https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=4908%3A27365

## QA

- visit https://global-nav-225.demos.haus/
- see that the "All Canonical" dropdown content matches the design

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
Hi @sowasred2012 thanks, this is very close! Just a few tiny niggles:

- [ ]  the meganav is out of alignment with the top navigation: 
image
- [ ] the rows are about .5rem too tall - can you please reduce the padding top/bottom to go from the current 60px height to around 48
- [ ] the dividers are too pronounced. Can you please match use the `$colors--dark-theme--border-low-contrast` for all dividers lines
- [ ] the descriptions are too pronounced. Can you please use the `$colors--dark-theme--text-muted` colour for them, and also for these muted headings: 
image

a lot more padding than in the design here: 
image

**Comment by sowasred2012** [comment]
@lyubomir-popov updated:
- adjusted max width of the content from 68rem to 72rem to match the top nav. The alignment is still out on the left hand side by .5rem, once this Vanilla fix is released it should be resolved: https://github.com/canonical/vanilla-framework/pull/4555
- I'm not sure where to take the top and bottom padding from - Vanilla's p styles are creating the height with margin and padding, reducing them throws out the alignment of the product name+logo, could we pair on this?

**Comment by lyubomir-popov** [comment]
@sowasred2012 a couple more comments:

- [ ] `u-no-padding` seems redefined within the navigation:

image

- [ ] since text is between horizontal dividers, we need to cancel the padding and margin like so:

image

- [ ] once the above is done, the logo needs to be adjusted so it sits in the middle of the line height. The above change results in it sitting a little too low: 
image

- [ ] please also add medium screen grid classes like so:
image

- [ ] can the navigation stay open when you switch to mobile? ATM as you rsize it appears/disappers when it reaches 620px from desktop to mobile. the other way round - opening it on mobile, then resizing to desktop resolution, is working meaning the nav stays open.

**Comment by sowasred2012** [comment]
@lyubomir-popov I've made those updates, the only one I haven't is:
> can the navigation stay open when you switch to mobile? ATM as you rsize it appears/disappers when it reaches 620px from desktop to mobile. the other way round - opening it on mobile, then resizing to desktop resolution, is working meaning the nav stays open.

I am not convinced we should do this in this module, since it only relates to the "All Canonical" dropdown. Keeping the entire mobile navigation open on resize would require the global nav to manipulate and know about markup outside of the element with the class it's initialized on, which it doesn't do at all at the moment - I think that should be handled in the implementation of the main navigation pattern.

**Comment by lyubomir-popov** [comment]
ok, makes sense about the last one. still waiting for the demo to refresh, we review once the changes appear.

**Comment by lyubomir-popov** [comment]
@sowasred2012 sorry noticed one more thing, can we make the links `#3097FF` (dark theme link colour)
image
At the moment, the resources (least important info) are farr too prominent because of the bold white:
image

**Comment by lyubomir-popov** [comment]
@sowasred2012 Sorry the tablet breakpoint needs a little more finessing, I did the following in the browser: (markup with browser-inlined code here https://pastebin.canonical.com/p/FqmyhJszPz/) 

image

**Comment by lyubomir-popov** [comment]
Thanks @sowasred2012 looks great!

**Comment by minkyngkm** [comment]
Looking good @sowasred2012! One thing I found is the global nav disappears on small screens. Do we have to fix this? 

global-nav

**Comment by sowasred2012** [comment]
> Looking good @sowasred2012! One thing I found is the global nav disappears on small screens. Do we have to fix this?
> 
> global-nav [ global-nav ](https://user-images.githubusercontent.com/57550290/188597833-3d01cacc-d2dc-45c8-847b-b36478265d85.gif) [ ](https://user-images.githubusercontent.com/57550290/188597833-3d01cacc-d2dc-45c8-847b-b36478265d85.gif)

@minkyngkm it's in the Menu :wink: 
Peek 2022-09-06 10-26

**Review by minkyngkm — APPROVED** [review]
LGTM! NIce work!🏅

**Pull request merged**
