### PR TITLE
Add Anbox Cloud to product list

### PR DESCRIPTION
**Pull request by lorumic**
## Done
- Added new entry for Anbox Cloud to product list

## QA
- Go to https://global-nav-266.demos.haus/
- Open the navigation
- Check the new entry for Anbox Cloud

## Screenshot

image

### CODE REVIEW

**Comment by aaryanporwal** [comment]
The canonical.com website doesn't use this `global-nav`, but I believe it should be mentioned there in the products section as well.

**Comment by lorumic** [comment]
> The canonical.com website doesn't use this `global-nav`, but I believe it should be mentioned there in the products section as well.

Good point - I've added a note to discuss this with the core team tomorrow.

**Comment by juanruitina** [comment]
I am inquiring about the best way to incorporate this.

**Comment by juanruitina** [comment]
We have incorporated Anbox Cloud to the global nav in #271. We can only list a limited selection of products as "featured", so we have added Anbox under "Also from Canonical" instead.

**Pull request closed without merging**
