### PR TITLE
WIP: Visual bugs

### LINKED ISSUE #249: Chevron right indentation on mobile doesn't match navigation dropdowns
On mobile the chevron for the global nav is too far to the right compared to other dropdown menu items

Screenshot 2023-01-18 at 16 00 33

### PR DESCRIPTION
**Pull request by steverydz**
## Done
- Fixed the chevron position on mobile
- Fixed the chevron colour on light themed navigation
- Fixed the top of the navigation being hidden under preceding navigation items on mobile

## QA
- Go to https://global-nav-250.demos.haus/demo
- Resize to mobile size
- Check that all the dropdown chevrons are aligned
- Check that the open "All Canonical" nav isn't hidden in mobile view

## Issue
Fixes #249, #251

## Screenshots
Screenshot 2023-01-18 at 16 00 33

### CODE REVIEW

**Comment by anthonydillon** [comment]
To be discussed in DA

**Comment by juanruitina** [comment]
@steverydz As discussed, feel free to proceed with this issue. I will work with UX and Visual on consolidating mobile navigation for the Ubuntu.com meganav and the microsites/global nav, but it will take a bit of time. We will keep you in the loop.

**Comment by steverydz** [comment]
Although this does fix alignment issues with the chevrons, I'm not happy to pursue this until we have a solution for closing the global nav on mobile. As it stands, it overtakes the page and cannot be closed which makes the site unusable.

**Comment by steverydz** [comment]
Closing in favour of https://github.com/canonical/global-nav/pull/254

**Pull request closed without merging**
