### PR TITLE
WD-2373 Implement new mobile side navigation

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Implement the new visual design for mobile navigation

## QA

- Check out the demo [here](https://global-nav-256.demos.haus/).
- Compare the menu implementation to the [visual design](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=1323%3A3714&t=qlM88womaW4j6D5q-0).

## Issue / Card

- [WD-2373](https://warthogs.atlassian.net/browse/WD-2373)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-2373]: https://warthogs.atlassian.net/browse/WD-2373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by steverydz — APPROVED** [review]
LGTM 👍 

Great work!

**Comment by juanruitina** [comment]
Some comments:

* Text for "Menu" button shouldn't change when opened. However, the button background should change to lighter gray (#333), same as the background for the menu items list.
* Background for menu items list should take 100% of the viewport's height as soon as it's opened.
* Navbar should remain visible at all times.
* All subnav (not only "All Canonical") should open with sliding, not dropdown.
* Can you apply the padding to the links/buttons, instead of the li element?

**Comment by pedoch** [comment]
> Some comments:
> 
> * Text for "Menu" button shouldn't change when opened. However, the button background should change to lighter gray (#333), same as the background for the menu items list.
> * Background for menu items list should take 100% of the viewport's height as soon as it's opened.
> * Navbar should remain visible at all times.
> * All subnav (not only "All Canonical") should open with sliding, not dropdown.
> * Can you apply the padding to the links/buttons, instead of the li element?

Hey @juanruitina a couple of these will be done when implementing the new navigation on the sites them selves since this is just for the global nav. The globalnav is just a plugin that attaches itself on the current navigation on the site.

- The background of the menu and changing of text will be will be done on the specific site itself.
- The other subnav will be made sliding navigations when the new navigation still is eventually implemented is the other sites.
- The menu items do not current take up the whole viewport because that's handle by the actually sites (using vanilla's navigation component). The global nav just attaches it's self to it.

But I have implemented the other changes you requested.

**Comment by juanruitina** [comment]
Thanks Ochuko for the clarification. Huge misunderstanding on my part, I thought global-nav covered the whole navigation on microsites, not that for "All Canonical" only. This should not go live until the rest can be handled via Vanilla or otherwise.

About the transition animation, can you please make sure it's disabled for users that have enabled `prefers-reduced-motion`? I'll also give some thought to the animation itself, when testing it I noticed it might induce motion sickness to some users. Android seems to use a subtlier transition, we can start there. Will be back to you on this.

**Comment by lyubomir-popov** [comment]
@ochuka partial QA [here ](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=5646%3A29099&t=OlMJRQ5vfzJ6AnzJ-1) - can we replace the logo with a tagged logo so we ca nQA the alignments properly?

**Comment by lyubomir-popov** [comment]
@pedoch just read your comments on the scope of this, and I agree with @juanruitina - we can't properly deploy (or even test) this until we see it at least in a demo form in the updated overall navigation with a tag logo etc. 

One comment on the animation - I was imagining all layers/levels to be on one plane, which slides left/right and is cropped by the screen. in other words, the child panels are simply floated next to each other, and clicking on them translates the entire thing left/right. Does that make sense?

**Comment by pedoch** [comment]
@lyubomir-popov I don't think floating them side-by-side will work. Because the navigation is like a nested tree. Having them floated next to each other will probably mean having to slide through other navigations in-between to get to the one needed. I think it best to have them stacked based on index and drawn out with their IDs like cards.

Also, I was tasked with seeing if I can override the non-globalnav navigation styles (basically the navigation in vanilla) from within the global-nav so we can test better and perhaps deploy. If it doesn't work then it may need to be done as a sprint within vanilla and rolled out to the sites. I wouldn't mind joining Vanilla for an iteration to get it done.

**Comment by bartaz** [comment]
@pedoch Couple things we can still do here along starting the work in Vanilla:

- [ ] in the global nav demo replace the Canonical logo with "tagged" Ubuntu logo as in here: https://vanillaframework.io/docs/examples/patterns/navigation/default-dark

- [ ] the spacing on the sliding menu needs to be updated, the hover effect on the items should highlight from right to left without padding/margin as on first level

First level: text aligned with logo above it, hover background from side to side
image

Second level: menu items have weird padding around, are not aligned with logo, hover background is touching text (not reaching from side to side):
image

**Comment by juanruitina** [comment]
@bartaz Aligning the menu items with the wordmark was a design [from Visual](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=1323%3A3714&t=fxlMkd0IDdzs5ovl-1), it should look fine with the tagged logo.

@lyubomir-popov I noticed the chevron is white in Vanilla navigation, and I reckon that makes it more noticeable and accessible (even if the current gray is technically valid). You OK with changing it from grey to white in the navigation?

@pedoch Some feedback on accessibility:

- Keyboard navigation skips “All Canonical”
- “Back” doesn’t change state on focus

I've also noticed menu items seem to have a different height on sublevels than on the top level. That might have to do with the way borders are handled on the global nav. It is rather noticeable when opening it: items should be aligned, and they take more space on the global nav. Can you have a look?

**Comment by pedoch** [comment]
I'll make the appropriate changes so we can test properly.

**Comment by lyubomir-popov** [comment]
thanks @pedoch lets have a pairing session once the logo is there and we can sort things out together

**Pull request closed without merging**
